### ISSUE TITLE
controller manager issues

### ISSUE THREAD

**Issue by cormachogan** [vKubeViewer/vkubeviewer#20]
Using the controller-manager from the docker repo, I noticed that there is none labeled latest. What we do have is a v5, which seems to be the more recent.

Therefore, I used v5 as the image:

export IMG=docker.io/vkubeviewer/controller-manager:v5

And followed this with a "make deploy". Unfortunately this has a failure when trying to start, and I don't know if this is due to it not being the latest controller manager, or something is not getting cleaned up correctly. Here are the logs from the startup:

```
cormac@pks-cli:~/vkubeviewer$ kubectl get pods -A
NAMESPACE            NAME                                              READY   STATUS             RESTARTS   AGE
default              zone-c-pod                                        1/1     Running            0          4h40m
kube-system          coredns-74ff55c5b-wlqhq                           1/1     Running            0          100d
kube-system          coredns-74ff55c5b-xgpfp                           1/1     Running            0          100d
kube-system          etcd-k8s-controlplane-01                          1/1     Running            1          128d
kube-system          kube-apiserver-k8s-controlplane-01                1/1     Running            1          128d
kube-system          kube-controller-manager-k8s-controlplane-01       1/1     Running            1          128d
kube-system          kube-flannel-ds-2vcxg                             1/1     Running            205        98d
kube-system          kube-flannel-ds-5b272                             1/1     Running            5          45d
kube-system          kube-flannel-ds-bnwvd                             1/1     Running            0          98d
kube-system          kube-flannel-ds-mksvc                             1/1     Running            1          98d
kube-system          kube-flannel-ds-rg4bk                             1/1     Running            1          98d
kube-system          kube-flannel-ds-v5dqz                             1/1     Running            0          45d
kube-system          kube-proxy-92tv4                                  1/1     Running            4          45d
kube-system          kube-proxy-9zrbm                                  1/1     Running            1          128d
kube-system          kube-proxy-gq2mr                                  1/1     Running            0          45d
kube-system          kube-proxy-lr8cx                                  1/1     Running            1          128d
kube-system          kube-proxy-mp4d4                                  1/1     Running            43         98d
kube-system          kube-proxy-nvcgl                                  1/1     Running            1          120d
kube-system          kube-proxy-qz6rl                                  1/1     Running            0          120d
kube-system          kube-scheduler-k8s-controlplane-01                1/1     Running            1          128d
kube-system          metrics-server-774b56d589-8js6k                   1/1     Running            0          82d
kube-system          vsphere-cloud-controller-manager-cfm8v            1/1     Running            0          128d
kube-system          vsphere-csi-controller-6ddf68d4f-gp4zg            6/6     Running            0          100d
kube-system          vsphere-csi-node-27k9v                            3/3     Running            0          120d
kube-system          vsphere-csi-node-2bhd2                            3/3     Running            12         45d
kube-system          vsphere-csi-node-67469                            3/3     Running            3          128d
kube-system          vsphere-csi-node-lfljf                            3/3     Running            518        98d
kube-system          vsphere-csi-node-lrcl4                            3/3     Running            0          45d
kube-system          vsphere-csi-node-rzbkq                            3/3     Running            4          120d
kube-system          vsphere-csi-node-xss9c                            3/3     Running            0          128d
vkubeviewer-system   vkubeviewer-controller-manager-64ffb78489-6zcq9   1/2     CrashLoopBackOff   2          35s
cormac@pks-cli:~/vkubeviewer$ kubectl describe pod vkubeviewer-controller-manager-64ffb78489-6zcq9 -n vkubeviewer-system
Name:         vkubeviewer-controller-manager-64ffb78489-6zcq9
Namespace:    vkubeviewer-system
Priority:     0
Node:         k8s-worker-04/10.27.51.26
Start Time:   Fri, 03 Sep 2021 15:25:27 +0100
Labels:       control-plane=controller-manager
              pod-template-hash=64ffb78489
Annotations:  <none>
Status:       Running
IP:           10.244.4.40
IPs:
  IP:           10.244.4.40
Controlled By:  ReplicaSet/vkubeviewer-controller-manager-64ffb78489
Containers:
  kube-rbac-proxy:
    Container ID:  docker://8a09c41886edd4b9d6da7c772b4dc131d73362b245df73ce21153da8ebd5eee6
    Image:         gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
    Image ID:      docker-pullable://gcr.io/kubebuilder/kube-rbac-proxy@sha256:db06cc4c084dd0253134f156dddaaf53ef1c3fb3cc809e5d81711baa4029ea4c
    Port:          8443/TCP
    Host Port:     0/TCP
    Args:
      --secure-listen-address=0.0.0.0:8443
      --upstream=http://127.0.0.1:8080/
      --logtostderr=true
      --v=10
    State:          Running
      Started:      Fri, 03 Sep 2021 15:25:28 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from vkubeviewer-controller-manager-token-fjpnw (ro)
  manager:
    Container ID:  docker://2f9b87b3cf0d091ebf5b03f4cf7054eefcb165fd043e0684f22adcf816db3c85
    Image:         docker.io/vkubeviewer/controller-manager:v5
    Image ID:      docker-pullable://vkubeviewer/controller-manager@sha256:6ad11540fc807f7cff07aa83016087c7df313f43fe09a64833d87a59f41ca01b
    Port:          <none>
    Host Port:     <none>
    Command:
      /manager
    Args:
      --health-probe-bind-address=:8081
      --metrics-bind-address=127.0.0.1:8080
      --leader-elect
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 03 Sep 2021 15:25:47 +0100
      Finished:     Fri, 03 Sep 2021 15:25:49 +0100
    Ready:          False
    Restart Count:  2
    Limits:
      cpu:     100m
      memory:  30Mi
    Requests:
      cpu:      100m
      memory:   20Mi
    Liveness:   http-get http://:8081/healthz delay=15s timeout=1s period=20s #success=1 #failure=3
    Readiness:  http-get http://:8081/readyz delay=5s timeout=1s period=10s #success=1 #failure=3
    Environment:
      GOVMOMI_USERNAME:  <set to the key 'GOVMOMI_USERNAME' in secret 'vc-creds-1'>  Optional: false
      GOVMOMI_PASSWORD:  <set to the key 'GOVMOMI_PASSWORD' in secret 'vc-creds-1'>  Optional: false
      GOVMOMI_URL:       <set to the key 'GOVMOMI_URL' in secret 'vc-creds-1'>       Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from vkubeviewer-controller-manager-token-fjpnw (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  vc-creds-1:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vc-creds-1
    Optional:    false
  vkubeviewer-controller-manager-token-fjpnw:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  vkubeviewer-controller-manager-token-fjpnw
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                            From               Message
  ----     ------     ----                           ----               -------
  Normal   Scheduled  <invalid>                      default-scheduler  Successfully assigned vkubeviewer-system/vkubeviewer-controller-manager-64ffb78489-6zcq9 to k8s-worker-04
  Normal   Pulled     <invalid>                      kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0" already present on machine
  Normal   Created    <invalid>                      kubelet            Created container kube-rbac-proxy
  Normal   Started    <invalid>                      kubelet            Started container kube-rbac-proxy
  Normal   Pulled     <invalid> (x3 over <invalid>)  kubelet            Container image "docker.io/vkubeviewer/controller-manager:v5" already present on machine
  Normal   Created    <invalid> (x3 over <invalid>)  kubelet            Created container manager
  Normal   Started    <invalid> (x3 over <invalid>)  kubelet            Started container manager
  Warning  BackOff    <invalid> (x6 over <invalid>)  kubelet            Back-off restarting failed container
cormac@pks-cli:~/vkubeviewer$ kubectl get pods -A
NAMESPACE            NAME                                              READY   STATUS             RESTARTS   AGE
default              zone-c-pod                                        1/1     Running            0          4h41m
kube-system          coredns-74ff55c5b-wlqhq                           1/1     Running            0          100d
kube-system          coredns-74ff55c5b-xgpfp                           1/1     Running            0          100d
kube-system          etcd-k8s-controlplane-01                          1/1     Running            1          128d
kube-system          kube-apiserver-k8s-controlplane-01                1/1     Running            1          128d
kube-system          kube-controller-manager-k8s-controlplane-01       1/1     Running            1          128d
kube-system          kube-flannel-ds-2vcxg                             1/1     Running            205        98d
kube-system          kube-flannel-ds-5b272                             1/1     Running            5          45d
kube-system          kube-flannel-ds-bnwvd                             1/1     Running            0          98d
kube-system          kube-flannel-ds-mksvc                             1/1     Running            1          98d
kube-system          kube-flannel-ds-rg4bk                             1/1     Running            1          98d
kube-system          kube-flannel-ds-v5dqz                             1/1     Running            0          45d
kube-system          kube-proxy-92tv4                                  1/1     Running            4          45d
kube-system          kube-proxy-9zrbm                                  1/1     Running            1          128d
kube-system          kube-proxy-gq2mr                                  1/1     Running            0          45d
kube-system          kube-proxy-lr8cx                                  1/1     Running            1          128d
kube-system          kube-proxy-mp4d4                                  1/1     Running            43         98d
kube-system          kube-proxy-nvcgl                                  1/1     Running            1          120d
kube-system          kube-proxy-qz6rl                                  1/1     Running            0          120d
kube-system          kube-scheduler-k8s-controlplane-01                1/1     Running            1          128d
kube-system          metrics-server-774b56d589-8js6k                   1/1     Running            0          82d
kube-system          vsphere-cloud-controller-manager-cfm8v            1/1     Running            0          128d
kube-system          vsphere-csi-controller-6ddf68d4f-gp4zg            6/6     Running            0          100d
kube-system          vsphere-csi-node-27k9v                            3/3     Running            0          120d
kube-system          vsphere-csi-node-2bhd2                            3/3     Running            12         45d
kube-system          vsphere-csi-node-67469                            3/3     Running            3          128d
kube-system          vsphere-csi-node-lfljf                            3/3     Running            518        98d
kube-system          vsphere-csi-node-lrcl4                            3/3     Running            0          45d
kube-system          vsphere-csi-node-rzbkq                            3/3     Running            4          120d
kube-system          vsphere-csi-node-xss9c                            3/3     Running            0          128d
vkubeviewer-system   vkubeviewer-controller-manager-64ffb78489-6zcq9   1/2     CrashLoopBackOff   3          94s
cormac@pks-cli:~/vkubeviewer$ kubectl logs vkubeviewer-controller-manager-64ffb78489-6zcq9 -n vkubeviewer-system manager
2021-09-03T14:27:18.075Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2021-09-03T14:27:18.437Z	INFO	setup	succeed to get login session to vSphere
2021-09-03T14:27:18.442Z	INFO	setup	succeed to create container view for Datastore
2021-09-03T14:27:18.444Z	INFO	setup	succeed to retrieve Datastore info
2021-09-03T14:27:18.451Z	ERROR	setup	unable to create Datastore	{"error": "datastoreinfoes.topology.vkubeviewer.com \"vsan-octo-cluster-b\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createDatastoreInfo
	/workspace/main.go:107
main.main
	/workspace/main.go:381
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.459Z	ERROR	setup	unable to create Datastore	{"error": "datastoreinfoes.topology.vkubeviewer.com \"vsan-octo-cluster-c\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createDatastoreInfo
	/workspace/main.go:107
main.main
	/workspace/main.go:381
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.462Z	ERROR	setup	unable to create Datastore	{"error": "datastoreinfoes.topology.vkubeviewer.com \"isilon-01\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createDatastoreInfo
	/workspace/main.go:107
main.main
	/workspace/main.go:381
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.465Z	ERROR	setup	unable to create Datastore	{"error": "datastoreinfoes.topology.vkubeviewer.com \"vsan-octo-cluster-a\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createDatastoreInfo
	/workspace/main.go:107
main.main
	/workspace/main.go:381
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.468Z	INFO	setup	succeed to create container view for HostSystem
2021-09-03T14:27:18.470Z	INFO	setup	succeed to retrieve HostSystem info
2021-09-03T14:27:18.474Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-k.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.477Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-j.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.480Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-l.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.486Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-i.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.489Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-h.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.493Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-f.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.497Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-g.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.518Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"esxi-dell-e.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
2021-09-03T14:27:18.521Z	ERROR	setup	unable to create Host	{"error": "hostinfoes.topology.vkubeviewer.com \"vcsa06-witness-01.rainpole.com\" already exists"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/log.(*DelegatingLogger).Error
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/log/deleg.go:144
main.createHostInfo
	/workspace/main.go:182
main.main
	/workspace/main.go:386
runtime.main
	/usr/local/go/src/runtime/proc.go:225
panic: stat /home/nonroot/.kube/config: no such file or directory

goroutine 1 [running]:
vkubeviewer/controllers.ListK8sNodes(0x0, 0x0, 0x0)
	/workspace/controllers/helper.go:71 +0x338
main.createNodeInfo(0x1ff5ef0, 0xc000636ac0, 0x200e2a8, 0xc00053cfc0, 0xc000014000, 0x0, 0x0)
	/workspace/main.go:194 +0x34
main.main()
	/workspace/main.go:391 +0x795
```

**Comment by cormachogan** [comment]
I don't have this issue when I do a **make build**, and then manually run a **bin/manager** - suggesting that we are missing the latest controller image on docker hub.
